### ISSUE TITLE
Netlify for the Bioconductor/BioC2020 repo

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BioC2020#10]
Hi @lpantano ,

I see that the Netlify GitHub app was installed 3 days ago in the Bioconductor organization per your request, and with access to the BioC2020 repo only. Just wanted to make sure that this was intended. Do you confirm that you need Netlify for the Bioconductor/BioC2020 repo? Thanks!

H.

**Comment by mtmorgan** [comment]
We exchanged info about this on slack https://community-bioc.slack.com/archives/CP8MQ3C9K/p1571401029001300 do you have reservations?

**Comment by hpages** [comment]
No it's fine. I don't have reservations (I'm not familiar with Netlify but it seems trustable). I missed the discussion on Slack so the notification email I received about this came a little out of the blue. Just wanted to make sure that everything was "as expected". Also good to know that another core member (you) is aware and accepted the app. Thanks!
