### ISSUE TITLE
Add sponsor logos to conference website

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/BioC2020#104]

**Comment by Liubuntu** [comment]
Hi @mdozmorov , F1000 just replied with the logo to be uploaded to the website home page. Currently, their marketing team is working on the details of sponsorship. I am not sure if you want to put the logo on now or later, but here it is. Let me know if you need a different size or anything else. 
![F1000Research-400x400](https://user-images.githubusercontent.com/12683977/86991520-529f7780-c16d-11ea-8103-9d6c273c3c96.png)

**Comment by mdozmorov** [comment]
It is added, I cropped it a bit. We can always change if needed.
