### ISSUE TITLE
Add presenters section to website with presenter instructions and links for presenters

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/BioC2020#110]
Email could work, also, but the website would be helpful to capture the details, to give a better big picture to presenters, and to reuse in the future if necessary.

**Comment by mdozmorov** [comment]
Need more details about the format of poster sessions, BOFs, lunch meetings, the award ceremony

**Comment by Liubuntu** [comment]
Hi @mdozmorov , I am not quite sure about the "workshop" to be submitted to the F1000Research, since only PPT/PPTX/PDF are accepted. http://bioc2020.bioconductor.org/instructions-for-presenters

**Comment by mdozmorov** [comment]
Perhaps, we can clarify that papers presenting "workflows" based on workshops can be submitted. The https://f1000research.com/gateways/bioconductor/about-this-gateway invites BioC2020 paper submission. As well as posters and slides, if one clicks "Submit" https://f1000research.com/gateways/bioconductor/for-authors/publish-your-research. Looks like any submission is welcome.

**Comment by seandavi** [comment]
The Bioc gateway is meant for manuscripts as well, as is outlined here: http://bioc2020.bioconductor.org/call-for-abstracts. Workshops submitted as "workflows" has been available since we started the channel several years ago. The slides and posters are welcome additions this year!

**Comment by mdozmorov** [comment]
Clarified on the website
