### ISSUE TITLE
Track issues across all workshops

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#118]
We need a way to follow progress on issues across several workshops, and even just to keep track of where issues have been filed. As an inelegant solution, I'll just post links to the issues I've filed here. 

- [x] https://github.com/cmirzayi/EpiForBioWorkshop2020/issues/1
- [x] https://github.com/PeteHaitch/BioC2020_DelayedArray_workshop/issues/2
- [x] https://github.com/hukai916/IntegratedChIPseqWorkshop/issues/1
- [x] https://github.com/haibol2016/ATACseqQCWorkshop/issues/2
- [x] https://github.com/LihuaJulieZhu/CRISPRseekGUIDEseqBioc2020Workshop/issues/1
- [x] https://github.com/Kayla-Morrell/CreateAPackage/issues/2
- [ ] https://github.com/LieberInstitute/recountWorkshop2020/issues/1
- [x] https://github.com/aedin/PCAworkshop/issues/1
- [ ] ~https://github.com/broadinstitute/BioC2020Workshop_AMARETTO-Hub/issues/1~ - canceled

**Comment by mdozmorov** [comment]
Incomplete workshops, not edited on ConferenceDirect

- [ ] https://github.com/montilab/hypeR-workshop/issues/1
- [ ] LieberInstitute/recountWorkshop2020#1 - Pkgdown missing

**Comment by mdozmorov** [comment]
No longer current.
