### ISSUE TITLE
BioC2020 badges

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#14]
@schifferl are you willing to design badges again? I created a logo issue at https://github.com/Bioconductor/BiocStickers/issues/99.

**Comment by schifferl** [comment]
@lwaldron happy to, will get to it just as soon as the logo is ready!

**Comment by lpantano** [comment]
I realized we need to put the logo on the web-page, @lwaldron, should we add this to the left menu bar?  below the list maybe?

https://github.com/Bioconductor/BiocStickers/tree/master/events/Bioc2020

**Comment by lwaldron** [comment]
Your idea sounds good to me @lpantano.

**Comment by schifferl** [comment]
Hi @lwaldron, here's the badge and we can make changes as needed. I've used my name, which is short, but longer names/organizations will fill much more of the space.

![BiocFront-2020](https://user-images.githubusercontent.com/3837776/76355874-6afca400-62eb-11ea-9d6f-6659002e65d8.png)
