### ISSUE TITLE
Add link to Aedin's child care spreadsheet

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#22]
This is an editable Google Docs spreadsheet with info on local child care options in Boston, curated by @aedin.

**Comment by lwaldron** [comment]
Use this link instead: https://rebrand.ly/bioc2020childcare

Any of @mdozmorov @lpantano @HelenaLC @fboehm willing to self-assign?

**Comment by lpantano** [comment]
@lwaldron, is the idea to add this table to the webpage in a separate section for special services?if yes, did we agree on the name of the new section?

**Comment by lwaldron** [comment]
To keep the list dynamic, perhaps just link to the spreadsheet rather than
copying it onto the website. For a page name, how about "Accessibility &
child care" or just "Accessibility" if that is too long?

**Comment by mdozmorov** [comment]
How about "Childcare options are [available](
https://rebrand.ly/bioc2020childcare)"? There is a pull request for this to
be added to the "Travel & Accommodation" page, but it can be changed.

**Comment by lpantano** [comment]
@mdozmorov can you add the link to be part of the side menu as Chilcare options below Travel & Acomodation? I really want to give maximum visibility and there was an agreement on that during the call, I think. If it gets to busy there we can move links around.

**Comment by mdozmorov** [comment]
@lpantano, yes, will do asap.
