### ISSUE TITLE
Fix dates and "developer day"

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#23]
The dates on these pages should be corrected:
* https://bioc2020.bioconductor.org/schedule-developer-day
* https://bioc2020.bioconductor.org/schedule-day-one
* https://bioc2020.bioconductor.org/schedule-day-two

And "Developer Day" should be renamed to "Community / Developer Day", until we come up with a better name. Any of @mdozmorov @lpantano @HelenaLC @fboehm willing to self-assign?

**Comment by csoneson** [comment]
Also remove the "Symposium" under "What"

**Comment by lwaldron** [comment]
Looks good, thank you @mdozmorov!
