### ISSUE TITLE
Update invited speakers

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#25]
See https://bioc2019.bioconductor.org/ (and https://github.com/bioconductor/bioc2019) for an example. Look for bio and photo on the internet, reach out to speaker if it doesn't exist.

Confirmed speakers so far are:
- [x] Rafael Irizarry ([link](https://rafalab.github.io/))
- [x] Caroline Uhler ([link](https://bsse.ethz.ch/department/people/detail-person.MTA1ODk1.TGlzdC8yNjY5LDEwNjI4NTM0MDk=.html))

@csoneson will you help to keep this issue up-to-date as speakers are confirmed?

**Comment by csoneson** [comment]
Yes, will do.

**Comment by csoneson** [comment]
- [x] Kylie Ariel Bemis ([link](https://kuwisdelu.github.io/))

**Comment by csoneson** [comment]
- [ ] Fei Chen ([link](https://www.insitubiology.org/))

**Comment by lpantano** [comment]
https://github.com/Bioconductor/BioC2020/pull/27 Thanks @HelenaLC for the first three

**Comment by HelenaLC** [comment]
FYI- (In case someone else does this before I have wifi again) there’s a typo in Rafa’s bio saying “he as” instead of “he has”.

**Comment by csoneson** [comment]
- [ ] Aaron Lun ([link](https://ltla.github.io/about/))
- [ ] X Shirley Liu ([link](https://liulab-dfci.github.io/))

**Comment by HelenaLC** [comment]
Okay, the last PR has all 6! Aaron's bio is my favorite, but he MAY provide another version he says.

**Comment by lwaldron** [comment]
Chuckling out loud... but yes do give Aaron a chance to provide another version before merging :D

**Comment by csoneson** [comment]
With #39 , the set of invited speakers is complete. A couple are still missing pictures though.

**Comment by mdozmorov** [comment]
Closing as complete
