### ISSUE TITLE
fix dates on top of each page

### ISSUE THREAD

**Issue by lpantano** [Bioconductor/BioC2020#3]
Need to update dates to July 29, 30-31 2020 in all pages

**Comment by mtmorgan** [comment]
It might be useful to use a `header.md` file like in https://github.com/Bioconductor/EuroBioc2019#new-pages which I think was added with https://github.com/Bioconductor/EuroBioc2019/commit/86927fc93350176d63e9269fd6f31139bef81b33

**Comment by mdozmorov** [comment]
@lpantano I made a PR that start addressing #3 (fix dates) from a forked repository. Noted it should be done through another branch. Please, add mdozmorov, and I'll do it.

**Comment by lpantano** [comment]
I added you @mdozmorov, you should be able to create a branch here and re-create the PR.

**Comment by mdozmorov** [comment]
Thank you, it works now. Created a PR through the "dev" branch.
