### ISSUE TITLE
add all organizers

### ISSUE THREAD

**Issue by lpantano** [Bioconductor/BioC2020#4]
Need to add all members to organizers committee, maybe we can split in groups since this year we have committees :)

- [x] Aedin Culhane
- [ ] Anthony Federico
- [ ] Ayush Raman
- [ ] Charlotte Soneson
- [ ] Deepak Tanwar
- [ ] Erica Feick
- [ ] Frederick Boehm
- [ ] Hector Corrada Bravo 
- [ ] Helena Crowell 
- [ ] Lauren Hsu 
- [x] Laurent Gatto
- [x] Lorena Pantano 
- [ ] Lori Shepherd 
- [x] Levi Waldron 
- [x] Matthew McCall
- [ ] Mikhail Dozmorov
- [x] Martin Morgan 
- [ ] Nathan Sheffield 
- [ ] Oriol Senan 
- [x] Peter Hickey 
- [ ] Qian Liu 
- [ ] Rafael Irizarry 
- [ ] Ricardo de Matos Simoes 
- [x] Sean Davis 
- [ ] Simone Bell 
- [ ] Simina Boca 
- [ ] Tom Carroll 
- [ ] Venu Thatikonda 
- [x] Vincent Carey 
- [ ] Zhezhen Wang 
- [ ] Anthony Federio

**Comment by mdozmorov** [comment]
Volunteering to address this #4 issue.

**Comment by lpantano** [comment]
Thanks, if you need help, let us know! Probably you'll need to ask people what to put there, Slack can be a good place for that or email directly.

**Comment by mdozmorov** [comment]
Closing as complete. Can be reopened if we would want to clean up the organizer's list
