### ISSUE TITLE
add Boston transportation information

### ISSUE THREAD

**Issue by lpantano** [Bioconductor/BioC2020#5]
Some information can be moved from previous year to this page:

https://github.com/Bioconductor/BioC2020/blob/master/docs/travel-accommodations.md

Like Airport and Boston transportation

**Comment by lpantano** [comment]
@HelenaLC ,

in case you want to take on this, if not unassigne :)

I will try to find some other conference in Boston, so we can use as template to add the Airport, and transportation information for now. 

Let me know, thanks

**Comment by HelenaLC** [comment]
Sure! Let me know what do add- i.e. any links from where I can extract relevant info.

**Comment by lpantano** [comment]
Erica  will send an email with information, then we can update :)

**Comment by HelenaLC** [comment]
Made a PR.
