### ISSUE TITLE
Docker link does not agree with workshop DESCRIPTION

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BioC2020#76]
Hi Mikhail @mdozmorov and Lorena @lpantano 

The Docker link in the [workshops page](https://bioc2020.bioconductor.org/workshops) for `Multi-omic Integration and Analysis of cBioPortal and TCGA data with MultiAssayExperiment` does not agree with the `DESCRIPTION` file in the workshop:

https://github.com/waldronlab/MultiAssayWorkshop/blob/0501f784d83eeb236cc06e2e3bbd86bb647ea4ed/DESCRIPTION#L49

```
DockerImage: mr148/multiassayworkshop:latest
```

For some reason, the link points to `waldronlab/multiassayworkshop`. 
Thank you for your help. 
-Marcel

**Comment by csoneson** [comment]
We have the same issue for our workshop (iSEE: Interactive visualization of SummarizedExperiment objects), where the GitHub username != the Docker Hub username. 

Workshop: https://github.com/iSEE/iSEEWorkshop2020
Docker image: `iseedevelopers/iseeworkshop2020:latest`

Thanks
Charlotte

**Comment by mdozmorov** [comment]
Thank you for pointing that out. This is because the table is manually
created. The current pull request fixes both issues, as well as corrects
titles. But in retrospect, we should have a package that would pull the
correct information from the DESCRIPTION files and generate the table
automatically. Can this be an idea for a hackathon?

Mikhail

**Comment by mdozmorov** [comment]
Pull request #77 closes it, when merged

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 
I'm not sure a package is necessary. Perhaps it can be done using an `.Rmd` file to generate the `.md` file. I can give it a try some time today.
-Marcel

**Comment by mdozmorov** [comment]
Thank you, Marcel. I'm not sure about the best way, have been thinking about a function that accepts a list of GitHub URLs, pulls workshop information from the DESCRIPTION files, and compiles the Markdown table. I can't get to it this week, please, help if you can.
Mikhail
