### ISSUE TITLE
Make edits to clarify meeting is virtual

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/BioC2020#86]

**Comment by csoneson** [comment]
A couple of specific details:
* Website currently says "live keynotes" - according to the last call, should be "pre-recorded keynotes"
* Distinction into "Developer/community day" and "Main conference" can be removed
* https://github.com/Bioconductor/BioC2020/blob/95ae8a671dd79871223777cbac878eb99d437c69/docs/_config.yml#L4 still says July 29-31

**Comment by mdozmorov** [comment]
Closed by PR #96, including _config.yaml fix
