### ISSUE TITLE
Update website with details of how to submit birds-of-a-feather session.

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/BioC2020#91]

**Comment by seandavi** [comment]
Need to define the actual opening and closing dates.

**Comment by mdozmorov** [comment]
Update the initial announcement, https://support.bioconductor.org/p/129518/

Open ASAP, suggested closing date is July 16

**Comment by lwaldron** [comment]
@lshep this is your announcement on the support site.

**Comment by lwaldron** [comment]
@mdozmorov your proposed dates are good (open currently, close July 16).

**Comment by mdozmorov** [comment]
Closed by PR #96
