### ISSUE TITLE
Should be #bioc2020-workshops (not bioc2019)

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#93]
See: https://github.com/Bioconductor/BioC2020/blob/06283e1413e789f859c69945cabd31c65d682d37/docs/workshops.Rmd#L8

**Comment by mdozmorov** [comment]
The #bioc2020-workshops channel does not seem to exist. Shall we create it, or reuse the current #bioworkshopbook? Favoring the former.

**Comment by LiNk-NY** [comment]
Fixed in 58593acfaa85368fcbf0e4e1c62d321e0603e269
