### ISSUE TITLE
Update day 1, day 2... schedules

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2020#94]
IMO, "Day 1", "Day 2", etc is more complicated than necessary because we will also have the platform schedule, especially since the schedule will be changing still. Perhaps just a single page, or link to a wiki at https://github.com/Bioconductor/BioC2020/wiki?

**Comment by mdozmorov** [comment]
We can do both, everyone has different preferences. The pull request #96 addresses multiple issues, and here's how the day 1 schedule will look like [in code](https://github.com/Bioconductor/BioC2020/pull/96/commits/b83320575c68e981b6d70efc8ce28c1e9ba4ec40) and visually

![image](https://user-images.githubusercontent.com/864945/85484900-ba629980-b595-11ea-97e4-5831c1dc73db.png)

**Comment by lwaldron** [comment]
This looks great to me. I was just trying to suggest minimal work but you’ve already done the work! One small thing, I think we agreed on the contributed talks being 4x10 minutes each, followed by 15 minutes of questions to all four speakers. I think you can go ahead and merge your PRs @mdozmorov.

**Comment by mdozmorov** [comment]
Yes, I was thinking to keep the schedule as short/informative as possible - Q&A is implied for each talk, with the exact timing to be determined.

**Comment by lwaldron** [comment]
Day 1 is completed now, 2-5 still blank.

**Comment by mdozmorov** [comment]
On my todo, the schedule issue should be fully completed within a couple of days
